# Site settings
title: Zack Meredith - Web Developer & Designer
email: zacharybmeredith@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey there! This site is a work-in-progress portfolio of works currently or recently in progress as well. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zackmeredith.github.io" # the base hostname & protocol for your site
twitter_username: zackmeredith
github_username:  zackmeredith

port: 4000

# Build settings
markdown: kramdown

sass:
  sass_dir: assets/css
  style: :nested

include: ['_includes/work']
exclude: ['design.sketch']