# Site settings
title: Zack Meredith - Web Developer & Designer
email: zacharybmeredith@gmail.com
description: My name is Zack Meredith, a lifelong musician turned Web Designer/Dev.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zackmeredith.github.io" # the base hostname & protocol for your site
twitter_username: zackmeredith
github_username:  zackmeredith

port: 4000

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: assets/css
  style: :compressed

include: ['_includes/work']
exclude: ['design.sketch']

#Plugins

gems:      [jekyll-assets, autoprefixer-rails]