#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'My name is Zack Meredith, a lifelong musician turned Web Designer/Dev. I believe that well designed works are engaging & a pleasure to experience.'
#   rel-author: 'https://plus.google.com/u/0/'
#   rel-publisher: 'https://plus.google.com/u/0/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: UA-61450131-1

#-------------------------------
# Work Section

projects:
- {name: NOBS Website Redesign, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: My Site, folder: 'proj-2', file: 'work/proj-2.html'}
